# This is a basic workflow to help you get started with Actions
# https://github.com/jedieaston/ungoogled-chromium-windows/blob/master/.github/workflows/build.yml

name: Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-15

    # https://github.com/reitermarkus/dotfiles/blob/7faa1caddd086e8fbb9c5e964285e5031a8d14a5/.github/workflows/ci.yml
    # Steps represent a sequence of tasks that will be executed as part of the job
    # see for cherry-picked patch: https://issues.chromium.org/issues/40277359
    steps:
      - name: Download dependencies and prep source
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer
        run: |
          brew install coreutils ccache &&
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git &&
          export PATH="$PATH:$(pwd)/depot_tools" &&
          export CCACHE_DIR="$(pwd)/ccache" &&
          mkdir chromium && cd chromium &&
          fetch --no-history ios &&
          cd src &&
          echo -e "[gn_args]\nuse_blink = true\nios_enable_code_signing = false\nuse_lld = false\nios_app_bundle_id_prefix = \"com.testblink001\"\nuse_partition_alloc = false\nsymbol_level = 0\nis_debug = false\nenable_nacl = false\nblink_symbol_level = 0\nv8_symbol_level = 0\n\ncc_wrapper=\"env CCACHE_SLOPPINESS=time_macros ccache\"\n" > ~/.setup-gn &&
          python3 ios/build/tools/setup-gn.py &&
          echo "PATH=$PATH" >> "$GITHUB_ENV" &&
          echo "CCACHE_DIR=$CCACHE_DIR" >> "$GITHUB_ENV"
      - name: Download workflow artifact
        uses: tech234a-alt/action-download-artifact@master
        if: always()
        continue-on-error: true
        with:
          workflow_conclusion: "completed"
          name: ccache
          if_no_artifact_found: warn
          check_artifacts: true
          ensure_latest: true
          skip_unpack: true
      - name: Zip restore
        continue-on-error: true
        run: |
          mv ccache.zip ccache_outer.zip && unzip -q -n ccache_outer.zip && rm ccache_outer.zip && unzip -q -n ccache.zip && rm ccache.zip
      - name: Compilation
        if: always()
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
        run: |
          ccache -M 30G && cd chromium/src && 
          timeout 315m autoninja -C out/Release-iphoneos content_shell
      - name: Zip cache
        if: always()
        continue-on-error: true
        run: |
          touch ccache.zip && rm ccache.zip && zip -q -r ccache.zip ccache
      - uses: actions/upload-artifact@v4
        continue-on-error: true
        if: always()
        with:
          name: ccache
          path: ccache.zip
      - name: Zip save
        continue-on-error: true
        if: always()
        run: |
          touch ccache.zip && rm ccache.zip && zip -q -r out.zip chromium/src/out/Release-iphoneos
      - uses: actions/upload-artifact@v4
        continue-on-error: true
        if: always()
        with:
          name: chromium-ios-zip
          path: out.zip
      - name: Cache stats
        if: always()
        continue-on-error: true
        run: |
          ccache -s
