# This is a basic workflow to help you get started with Actions
# https://github.com/jedieaston/ungoogled-chromium-windows/blob/master/.github/workflows/build.yml

name: Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13

    # https://github.com/reitermarkus/dotfiles/blob/7faa1caddd086e8fbb9c5e964285e5031a8d14a5/.github/workflows/ci.yml
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download source and Run Build
        run: |
          brew install coreutils &&
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git &&
          export PATH="$PATH:$(pwd)/depot_tools" &&
          mkdir chromium && cd chromium &&
          fetch --no-history ios &&
          cd src &&
          echo -e "[gn_args]\nuse_blink = true\nios_enable_code_signing = false\n" > ~/.setup-gn &&
          python3 ios/build/tools/setup-gn.py &&
          echo "PATH=$PATH" >> "$GITHUB_ENV"
      - uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: chromium-ios-zip
          path: out.zip
      - name: Zip restore
        continue-on-error: true
        run: |
          unzip out.zip -n -d chromium/src/out &&
          rm out.zip
      - name: Compilation
        run: |
          cd chromium/src &&
          timeout 2m autoninja -C out/Debug-iphoneos content_shell
      - name: Zip save
        if: always()
        continue-on-error: true
        run: |
          zip -r out.zip chromium/src/out/Debug-iphoneos
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: chromium-ios-zip
          path: chromium/src/out/Debug-iphoneos/out.zip
